---
- hosts: 172.31.25.218
  become: yes
  tasks:
  - include_tasks: myfiles.yml

  - name: install webserver 
    apt: 
      name: apache2
      state: present

  - name: copy index.html file into node side
    copy:
       src: myindex.html
       dest: /var/www/html/index.html

  - name: copy myindex.j2 file into node side 
    template:
         src: myindex.j2
         dest: /var/www/html/index.html



     
