---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want install apache2 webserver 
    apt:
      name: apache2 
      state: present

  - name: i want to start webserver
    service:
       name: apache2
       state: restarted


